data:
  columns:
    - 
  target_column: Aggregate rating
  id_columns:
    - Restaurant ID
    - Restaurant Name
  categorical_columns:
    - Restaurant Name
    - City
    - Address
    - Locality
    - Locality Verbose
    - Cuisines
    - Currency
    - Has Table booking
    - Has Online delivery
    - Is delivering now
    - Switch to order menu
    - Rating color
    - Rating text
  numerical_columns:
    - Restaurant ID
    - Country Code
    - Longitude
    - Latitude
    - Average Cost for two
    - Price range
    - Votes
  drop_columns:
    - Rating color       
    - Rating text
    - Locality        
    - Locality Verbose  
    - Address
    - Longitude
    - Latitude
    - Restaurant Name
    - Switch to order menu