HERO_HTML = """
<div class="hero">
    <div class="hero-label">✦ Machine Learning · Regression Model</div>
    <h1 class="hero-title">Restaurant <em>Rating</em><br>Predictor</h1>
    <p class="hero-sub" style="text-align: center; margin: 0 auto; width: 100%;">
        Enter your restaurant's details below and let the model estimate it's aggregate rating with precision.
    </p>
    <div class="divider">
        <div class="divider-line"></div>
        <div class="divider-dot"></div>
        <div class="divider-line"></div>
    </div>
</div>
"""

SECTION_LOCATION_HTML = '<div class="section-card"><div class="section-title">📍 Location & <span>Currency</span></div>'
SECTION_COST_HTML     = '<div class="section-card"><div class="section-title">💰 Cost & <span>Popularity</span></div>'
SECTION_SERVICE_HTML  = '<div class="section-card"><div class="section-title">🛎️ Service <span>Options</span></div>'
SECTION_PRICE_HTML    = '<div class="section-card"><div class="section-title">🍽️ Price Range & <span>Cuisine</span></div>'
SECTION_CLOSE_HTML    = '</div>'

FOOTER_HTML = """
<p class="footer-note">Predictions are generated by a regression model trained on restaurant data.</p>
"""

def result_banner_html(whole, decimal, star_str, verdict, city, cuisine_str, price_label, votes):
    return f"""
    <div class="result-banner">
        <div class="result-label">✦ Predicted Aggregate Rating</div>
        <div class="result-score">{whole}<sup>.{decimal}</sup></div>
        <div class="result-stars">{star_str}</div>
        <div class="result-verdict">{verdict}</div>
        <div class="chip-row">
            <div class="chip">📍 {city}</div>
            <div class="chip">🍽️ {cuisine_str}</div>
            <div class="chip">💸 {price_label}</div>
            <div class="chip">🗳️ {votes:,} votes</div>
        </div>
    </div>
    """